In [8]:
import numpy as np # it is use to create a array


In [9]:
arr1=[12,344,2234,432,3432,443]
print(arr1)
arr2=np.array(arr1)
print(type(arr2))


[12, 344, 2234, 432, 3432, 443]
<class 'numpy.ndarray'>


In [10]:
arr5=list(range(1,10))
print(arr5)
print(type(arr5))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [11]:
a=12,34,4
type(a)

tuple

In [12]:
lavesh=np.array(arr1)
print(type(lavesh))


<class 'numpy.ndarray'>


In [13]:
arr2=list(range(1,20))
print(type(arr2))
arr2=np.array(arr2)
print(arr2)

<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
a3=np.zeros((1,22))
print(a3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
a4=np.ones((2,4))
print(a4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
a5=np.arange(1,4)
print(a5)

[1 2 3]


In [21]:
np.linspace(1,66,6)

array([ 1., 14., 27., 40., 53., 66.])

In [22]:
np.arange(1,30).reshape(10,3)


ValueError: cannot reshape array of size 29 into shape (10,3)

In [23]:
np.random.randint(1,5,9)

array([1, 3, 2, 1, 2, 4, 2, 1, 2], dtype=int32)

In [26]:
np.random.randint(1,5,(5,2))

array([[2, 1],
       [4, 1],
       [3, 1],
       [1, 4],
       [4, 1]], dtype=int32)

In [27]:
np.random.random(10)

array([0.6527135 , 0.63759895, 0.5723487 , 0.16958834, 0.17050541,
       0.36525671, 0.99250882, 0.90612395, 0.75359407, 0.39839472])

In [37]:
a5=np.arange(60).reshape(10,6)
a5.dtype
a5.ndim

TypeError: 'numpy.dtypes.Int64DType' object is not callable

In [38]:
arr5.fla

AttributeError: 'list' object has no attribute 'flatten'

In [39]:
lst_2d=[[1,2,3,],[2,3,4]]
lst_2d

[[1, 2, 3], [2, 3, 4]]

In [40]:
np.array(lst_2d)

array([[1, 2, 3],
       [2, 3, 4]])

In [41]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [43]:
arr[10]# for find the perticular element in array

np.int64(10)

In [47]:
arr[0:20:4]


array([ 0,  4,  8, 12, 16])

In [61]:
arr9=np.arange(60).reshape(12,5)


In [63]:
arr9[8:12,3:5]

NameError: name 'arr9' is not defined

In [62]:
arr9[11][-1]

np.int64(59)

In [65]:
arr9=np.arange(60).reshape(12,5)
print(arr9)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


In [71]:
arr9[6:8,3:5]

array([[33, 34],
       [38, 39]])

In [72]:
arr9[11][-1]

np.int64(59)

In [73]:
arr[-1][-1]

np.int64(59)

In [74]:
arr[-1,-1]

np.int64(59)

In [77]:
arr9[11:,-1][0]

np.int64(59)

###  3D array

In [81]:
arr7=np.arange(225).reshape(5,15,3)
arr7

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [87]:
arr7[4][14][2]

np.int64(224)